version: "3.3"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: db_music

  web:
    image: web
    build: .
    command: python app.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: db_music
    links:
      - postgres
    depends_on:
      - postgres
  