version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - postgres
  postgres:
    image: postgres
    port: 5432
    username: postgres
    password: psql
    host: localhost
    databaseName: db_music
    jdbc-url: jdbc:postgresql://${services.postgres.host}:${services.postgres.port}/${services.postgres.databaseName}

volumes:
  logvolume01: {}