version: "3.3"  # optional since v1.27.0
   
services:
  postgres:
    image: postgres:latest
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    restart: always
    ports:
        - "80:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: db_music
      PGDATA: "/var/lib/postgresql/data/pgdata"

  web:
    image: web
    build: .
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: db_music
    links:
      - postgres
    depends_on:
      - postgres